rabbitmq:
  image: rabbitmq:3.6.1-management
  name: rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"

mysql:
  image: mysql:5.6.37
  name: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=mypass

memcached1:
  image: memcached
  name: mc1
  ports:
    - "11211:11211"

#memcached2:
#  image: memcached
#  name: mc2
#  ports:
#    - "11212:11211"
